### ISSUE TITLE
cmd is not always cleared after exiting poe

### ISSUE THREAD

**Issue by dertuxmalwieder** [prodhe/poe#1]
On Windows 10, `poe` sometimes does not clear the terminal after having been quit:

![Screenshot](https://user-images.githubusercontent.com/125629/42501148-5e592680-8433-11e8-8110-a7bd1951ba3a.png)

**Comment by prodhe** [comment]
I remember this being an issue on MacOS as well from time to time. The fault was in the underlying tcell package, but that has been fixed upstream for a long time.

Closing this issue.
