### ISSUE TITLE
The PowerShell is not completely cleared after exiting poe 

### ISSUE THREAD

**Issue by dertuxmalwieder** [prodhe/poe#2]
Loosely related to #1 - I guess. The visible part is blue - but there is a large white area below it:
![scroll up](https://user-images.githubusercontent.com/125629/42501492-235d2eea-8434-11e8-8c71-2b552186c58a.png)
![scroll down](https://user-images.githubusercontent.com/125629/42501493-2384aca4-8434-11e8-9328-515d725cd2aa.png)

**Comment by prodhe** [comment]
See #1 .
